# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":today:"
    replace: "{{mydate}}"
    label: "Insert today's date, such as 2022/01/15"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"
  - trigger: ":tomorrow:"
    replace: "{{mytime}}"
    label: "Insert tomorrow's date, such as 2022/01/16"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Y/%m/%d"
          offset: 86400
  - trigger: ":yesterday:"
    replace: "{{mytime}}"
    label: "Insert yesterday's date, such as 2022/01/14"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Y/%m/%d"
          offset: -86400
  - trigger: ":time:"
    replace: "{{mytime}}"
    label: "Insert the current time, such as 12:00:00"
    vars:
      - name: mytime
        type: date
        params:
          format: "%T"
  - triggers: [":accountNum:"]
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "security find-generic-password -a 'accountNum' -w"
